d:\close\shutdown -f -s \\A-THOMPSON  
                                                     
d:\close\shutdown -f -s \\ALISON-HOLLANDS                                                              
d:\close\shutdown -f -s \\ANNE-AVERY                                                                   
d:\close\shutdown -f -s \\ARTHUR-MOULD
                                       
d:\close\shutdown -f -s \\BEVERLEY-SMITH                                                               
d:\close\shutdown -f -s \\BORA-TURAN                                                                   
d:\close\shutdown -f -s \\BRIAN_YOUNG                                                                  
d:\close\shutdown -f -s \\CANDY-VALLERINE                                                              
d:\close\shutdown -f -s \\CLAIRE-LAWDEN2                                                               
d:\close\shutdown -f -s \\DAWN-LANGHAM                                                                 
d:\close\shutdown -f -s \\DEAN-KIRBY                                                                   
d:\close\shutdown -f -s \\DEBBIE-DONNELLY                                                              
d:\close\shutdown -f -s \\DEBORAH-HUSSEY                                                               
d:\close\shutdown -f -s \\DOUGLAS-PEFFERS                                                              
d:\close\shutdown -f -s \\ELEANOR-DALLMAN                                                              
d:\close\shutdown -f -s \\FRAN-EDWARDS                                                                 
d:\close\shutdown -f -s \\GILL-OWEN                                                                    
d:\close\shutdown -f -s \\GRAPHICS-WORKST                                                              
d:\close\shutdown -f -s \\HEATHER-GREENHO                                                              
d:\close\shutdown -f -s \\HELEN-TONKS                                                                  
d:\close\shutdown -f -s \\HELEN-WATT2                                                                  
d:\close\shutdown -f -s \\IT-300PL-0938                                                                
d:\close\shutdown -f -s \\J-MOSS                                                                       
d:\close\shutdown -f -s \\K-TORNIAINEN                                                                 
d:\close\shutdown -f -s \\L-LEAMON                                                                     
d:\close\shutdown -f -s \\LESLIE-ANSCOMBE                                                              
d:\close\shutdown -f -s \\LINDSEY-PATTO                                                                
d:\close\shutdown -f -s \\LUCY-ROBACK                                                                  
d:\close\shutdown -f -s \\N-SCARBROUGH                                                                 
d:\close\shutdown -f -s \\NICOLA-JOWSEY                                                                
d:\close\shutdown -f -s \\NIKOLA-PERERA                                                                
d:\close\shutdown -f -s \\P-THISTLETON                                                          
d:\close\shutdown -f -s \\PAUL-GREY                                                                    
d:\close\shutdown -f -s \\PETER-DUCKWORTH                                                              
d:\close\shutdown -f -s \\PR3B11E0                                                            
d:\close\shutdown -f -s \\S-D-SOUZA                                                                    
d:\close\shutdown -f -s \\SARAH-BENNETT                                                                
d:\close\shutdown -f -s \\SARAH-LUGG                                                                   
d:\close\shutdown -f -s \\SHARON-BURNS                                                                 
d:\close\shutdown -f -s \\SUE-RICE                                                                     
d:\close\shutdown -f -s \\TERRIE-WILLIAMS                                                              
d:\close\shutdown -f -s \\TIM-DAVIES                                                                   
d:\close\shutdown -f -s \\VAL-DOBBS                                                                    
d:\close\shutdown -f -s \\VALERIE-WENTWOR                                                              

